### ISSUE TITLE
Change the picture with DevFest Siliguri 2019 picture

### ISSUE THREAD

**Issue by debajit13** [Google-Developer-Groups-Siliguri/devfest-2022-website#16]
Remove this picture - 
![Screenshot 2022-10-19 at 10 37 59 AM](https://user-images.githubusercontent.com/42708550/196602594-40e33714-8eb6-4e3f-b36a-d4d84510a83f.png)

Add this picture - 
![Devfest 2019](https://user-images.githubusercontent.com/42708550/196603346-2f03be0f-5d7e-4257-a0c5-841d9e8f0ef1.jpeg)

**Comment by Das-Swarup** [comment]
Done
